### PR TITLE
New Code Pattern changes For React UI

### PR DESCRIPTION
**Pull request by MuthuSundaravadivel**

### CODE REVIEW

**Comment by lsteck** [comment]
Looks good to me.  After talking with @seansund We have a couple asks.

1. Could you pull up the client code up to the project root and combine the two package.json files into one.  Then modify the `npm run dev` script to start both the client and server to make it easier for the developer to run in "live mode".
2. Could you look at [this](https://github.ibm.com/seansund/template-node-react/blob/master/src/components/products/ProductListView.tsx) and see if you can restructure the modules to make it easier to add/remove them?  The idea is to design the modules so that we pass the function to load the data and the function to notify of events as props to the UI Pattern component. Then an app can be built by stringing the UI Pattern components together.  

Thanks!

**Comment by MuthuSundaravadivel** [comment]
@lsteck @seansund @mjperrins  When I am trying to run the project on open Shift. The pipeline got failed in the Test stage(Sonar Qube )Section. Because its referring Client folder even though I have removed client reference in Docker File and source directory. But the client reference its available Pipeline task (ibm-nodejs-test-v2-0-1). But it's common for all node js project. I will not able to modify it. Either I have to create a new one for all client reference task.   Please suggest How do I handle it?

**Comment by MuthuSundaravadivel** [comment]
@lsteck  I have updated the README file. Please check and let me know.  We don't have client folder now so we need to update the node scripts in Package.json. I have done the following test using new  React code patterns.

1. I have checked the application in Openshift Cluster. Whether all stages in the pipeline and Tekton task getting passed or not. It's working perfectly fine.
2. Inventory-management-ui-solution and Inventory-management-bff-solution API connection working fine. Please let me know if you need any further clarification

**Comment by mjperrins** [comment]
Have you updated the `dev` branch on the inventory solution to be built on this level of UI code ? we need to make sure the starter kit, the solution are in sync once we release to `main` branch

**Pull request merged**
