### PR TITLE
Dockerfile updated to pass all the Red Hat Certification requirements

### PR DESCRIPTION
**Pull request by manojjahgirdar**
The Dockerfile now passes all the following Tests on Red Hat Certification:
- [x] `is_rhel`
- [x] `has_licenses`
- [x] `rpm_list_successful`
- [x] `not_running_privileged`
- [x] `not_running_as_root`
- [x] `name_label_exists`
- [x] `vendor_label_exists`
- [x] `version_label_exists`
- [x] `release_label_exists`
- [x] `good_tags`
- [x] `good_layer_count`
- [x] `free_of_critical_vulnerabilities`
- [ ] `free_of_important_vulnerabilities`
- [x] `non_inherited_base_label_name`
- [x] `non_inherited_base_label_vendor`
- [x] `non_inherited_base_label_description`
- [x] `non_inherited_base_label_summary`
- [x] `has_base_rh_image`
- [x] `ubi_content_ok`
- [x] `has_under_40_layers`

>Note: At times the tests `free_of_critical_vulnerabilities` or `free_of_important_vulnerabilities` may fail if the `ubi8/nodejs-12` image has any [known vulnerabilities](https://catalog.redhat.com/software/containers/ubi8/nodejs-12/5d3fff015a13461f5fb8635a?gti-tabs=unauthenticated&container-tabs=security).

### CODE REVIEW

**Comment by bwoolf1** [comment]
LGTM. Nice job.

@csantanapr:
- This is built from ubi8/nodejs-12. Do you want to build it from ubi8/nodejs-14?
- Do you want the security update command commented out or not commented out by default?
- What do you think of the default values for version and release being the same as those for the UBI the image is built from?

**Comment by csantanapr** [comment]
Using nodejs 14 is better, please adjust the app if there is any problems with the app and nodejs 14

Leaving the update, I commented is ok

Labels look ok, user eventually would adjust to their needs.

**Comment by bwoolf1** [comment]
@csantanapr: What updates do you want to this PR to approve it? Please document these requests for @manojjahgirdar. Thanks.

**Comment by manojjahgirdar** [comment]
- I have tried building the Dockerfile with both `ubi8/nodejs12:1-77` and `ubi8/nodejs14:1-28`. The Build fails with the following error when using `ubi8/nodejs14:1-28`:
  ```
   => ERROR [builder 7/9] RUN npm ci                                                                      26.5s
  ------
   > [builder 7/9] RUN npm ci:
  #11 25.34
  #11 25.34 > node-sass@4.12.0 install /opt/app-root/src/node_modules/node-sass
  #11 25.34 > node scripts/install.js
  #11 25.34
  #11 25.69 Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-83_binding.node
  #11 26.00 Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-83_binding.node":
  #11 26.00
  #11 26.00 HTTP error 404 Not Found
  #11 26.00
  #11 26.00 Hint: If github.com is not accessible in your location
  #11 26.00       try setting a proxy via HTTP_PROXY, e.g.
  #11 26.00
  #11 26.00       export HTTP_PROXY=http://example.com:1234
  #11 26.00
  #11 26.00 or configure npm proxy via
  #11 26.00
  #11 26.00       npm config set proxy http://example.com:8080
  #11 26.01
  #11 26.01 > node-sass@4.12.0 postinstall /opt/app-root/src/node_modules/node-sass
  #11 26.01 > node scripts/build.js
  #11 26.01
  #11 26.12 Building: /usr/bin/node /opt/app-root/src/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
  #11 26.19 gyp info it worked if it ends with ok
  #11 26.19 gyp verb cli [
  #11 26.19 gyp verb cli   '/usr/bin/node',
  #11 26.19 gyp verb cli   '/opt/app-root/src/node_modules/node-gyp/bin/node-gyp.js',
  #11 26.19 gyp verb cli   'rebuild',
  #11 26.19 gyp verb cli   '--verbose',
  #11 26.19 gyp verb cli   '--libsass_ext=',
  #11 26.19 gyp verb cli   '--libsass_cflags=',
  #11 26.19 gyp verb cli   '--libsass_ldflags=',
  #11 26.19 gyp verb cli   '--libsass_library='
  #11 26.19 gyp verb cli ]
  #11 26.19 gyp info using node-gyp@3.8.0
  #11 26.19 gyp info using node@14.16.0 | linux | x64
  #11 26.19 gyp verb command rebuild []
  #11 26.19 gyp verb command clean []
  #11 26.21 gyp verb clean removing "build" directory
  #11 26.21 gyp verb command configure []
  #11 26.21 gyp verb check python checking for Python executable "python2" in the PATH
  #11 26.22 gyp verb `which` failed Error: not found: python2
  #11 26.22 gyp verb `which` failed     at getNotFoundError (/opt/app-root/src/node_modules/which/which.js:13:12)
  #11 26.22 gyp verb `which` failed     at F (/opt/app-root/src/node_modules/which/which.js:68:19)
  #11 26.22 gyp verb `which` failed     at E (/opt/app-root/src/node_modules/which/which.js:80:29)
  #11 26.22 gyp verb `which` failed     at /opt/app-root/src/node_modules/which/which.js:89:16
  #11 26.22 gyp verb `which` failed     at /opt/app-root/src/node_modules/isexe/index.js:42:5
  #11 26.22 gyp verb `which` failed     at /opt/app-root/src/node_modules/isexe/mode.js:8:5
  #11 26.22 gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
  #11 26.22 gyp verb `which` failed  python2 Error: not found: python2
  #11 26.22 gyp verb `which` failed     at getNotFoundError (/opt/app-root/src/node_modules/which/which.js:13:12)
  #11 26.22 gyp verb `which` failed     at F (/opt/app-root/src/node_modules/which/which.js:68:19)
  #11 26.22 gyp verb `which` failed     at E (/opt/app-root/src/node_modules/which/which.js:80:29)
  #11 26.22 gyp verb `which` failed     at /opt/app-root/src/node_modules/which/which.js:89:16
  #11 26.22 gyp verb `which` failed     at /opt/app-root/src/node_modules/isexe/index.js:42:5
  #11 26.22 gyp verb `which` failed     at /opt/app-root/src/node_modules/isexe/mode.js:8:5
  #11 26.22 gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
  #11 26.22 gyp verb `which` failed   code: 'ENOENT'
  #11 26.22 gyp verb `which` failed }
  #11 26.22 gyp verb check python checking for Python executable "python" in the PATH
  #11 26.23 gyp verb `which` failed Error: not found: python
  #11 26.23 gyp verb `which` failed     at getNotFoundError (/opt/app-root/src/node_modules/which/which.js:13:12)
  #11 26.23 gyp verb `which` failed     at F (/opt/app-root/src/node_modules/which/which.js:68:19)
  #11 26.23 gyp verb `which` failed     at E (/opt/app-root/src/node_modules/which/which.js:80:29)
  #11 26.23 gyp verb `which` failed     at /opt/app-root/src/node_modules/which/which.js:89:16
  #11 26.23 gyp verb `which` failed     at /opt/app-root/src/node_modules/isexe/index.js:42:5
  #11 26.23 gyp verb `which` failed     at /opt/app-root/src/node_modules/isexe/mode.js:8:5
  #11 26.23 gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
  #11 26.23 gyp verb `which` failed  python Error: not found: python
  #11 26.23 gyp verb `which` failed     at getNotFoundError (/opt/app-root/src/node_modules/which/which.js:13:12)
  #11 26.23 gyp verb `which` failed     at F (/opt/app-root/src/node_modules/which/which.js:68:19)
  #11 26.23 gyp verb `which` failed     at E (/opt/app-root/src/node_modules/which/which.js:80:29)
  #11 26.23 gyp verb `which` failed     at /opt/app-root/src/node_modules/which/which.js:89:16
  #11 26.23 gyp verb `which` failed     at /opt/app-root/src/node_modules/isexe/index.js:42:5
  #11 26.23 gyp verb `which` failed     at /opt/app-root/src/node_modules/isexe/mode.js:8:5
  #11 26.23 gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
  #11 26.23 gyp verb `which` failed   code: 'ENOENT'
  #11 26.23 gyp verb `which` failed }
  #11 26.23 gyp ERR! configure error
  #11 26.23 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
  #11 26.23 gyp ERR! stack     at PythonFinder.failNoPython (/opt/app-root/src/node_modules/node-gyp/lib/configure.js:484:19)
  #11 26.23 gyp ERR! stack     at PythonFinder.<anonymous> (/opt/app-root/src/node_modules/node-gyp/lib/configure.js:406:16)
  #11 26.23 gyp ERR! stack     at F (/opt/app-root/src/node_modules/which/which.js:68:16)
  #11 26.23 gyp ERR! stack     at E (/opt/app-root/src/node_modules/which/which.js:80:29)
  #11 26.23 gyp ERR! stack     at /opt/app-root/src/node_modules/which/which.js:89:16
  #11 26.23 gyp ERR! stack     at /opt/app-root/src/node_modules/isexe/index.js:42:5
  #11 26.23 gyp ERR! stack     at /opt/app-root/src/node_modules/isexe/mode.js:8:5
  #11 26.23 gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
  #11 26.23 gyp ERR! System Linux 5.10.25-linuxkit
  #11 26.23 gyp ERR! command "/usr/bin/node" "/opt/app-root/src/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
  #11 26.23 gyp ERR! cwd /opt/app-root/src/node_modules/node-sass
  #11 26.23 gyp ERR! node -v v14.16.0
  #11 26.23 gyp ERR! node-gyp -v v3.8.0
  #11 26.23 gyp ERR! not ok
  #11 26.23 Build failed with error code: 1
  #11 26.24 npm ERR! code ELIFECYCLE
  #11 26.24 npm ERR! errno 1
  #11 26.25 npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
  #11 26.25 npm ERR! Exit status 1
  #11 26.25 npm ERR!
  #11 26.25 npm ERR! Failed at the node-sass@4.12.0 postinstall script.
  #11 26.25 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  #11 26.28
  #11 26.28 npm ERR! A complete log of this run can be found in:
  #11 26.28 npm ERR!     /opt/app-root/src/.npm/_logs/2021-05-05T07_33_23_202Z-debug.log
  ------
  executor failed running [/bin/sh -c npm ci]: exit code: 1
  ```

- Hence I have used `ubi8/nodejs12:1-77` which is still a better version than the one currently being used which is `ubi8/nodejs12:1-52`.

- Here is a confirmation that the Dockerfile builds successfully with `ubi8/nodejs12:1-77`:
Screenshot 2021-05-05 at 1 02 00 PM

- And here is the proof that it fails with `ubi8/nodejs14:1-28`:
Screenshot 2021-05-05 at 1 03 51 PM

- Adjusting the application to work with `ubi8/nodejs14:1-28` is out of my scope.

- I have also commented the command for updating the image security content.

**Comment by bwoolf1** [comment]
@manojjahgirdar: Why are you building this from nodejs-12? You updates the others to build from ubi8/nodejs-14:1-28.1618434924.

**Comment by manojjahgirdar** [comment]
> @manojjahgirdar: Why are you building this from nodejs-12? You updates the others to build from ubi8/nodejs-14:1-28.1618434924.

@bwoolf1 because the image fails to build on nodejs 14, I have explained in detail with screenshots here: <https://github.com/IBM/template-node-react/pull/21#issuecomment-832484857>

**Comment by manojjahgirdar** [comment]
@csantanapr,
This passes all the tests except for the `gitops` one. The logs says the following:
```
unable to find result referenced by param "helm-url" in "gitops": Could not find result with name helm-url for task run helm-release
```
Screenshot 2021-05-06 at 1 03 56 AM

what does this mean?

**Comment by manojjahgirdar** [comment]
@csantanapr, Here is the verification that the app still works on OpenShift, using the Toolkit pipeline to build and deploy.

Screenshot 2021-05-06 at 11 52 03 PM

**Comment by manojjahgirdar** [comment]
Note to the reviewer:  The Dockerfile still uses nodejs-12 instead of nodejs-14 because the latter breaks the build, and here are more for details about it : <https://github.com/IBM/template-node-react/pull/21#issuecomment-832484857>

**Review by csantanapr — APPROVED** [review]
LGTM

**Review by csantanapr — COMMENTED** [review]
LGTM

**Pull request merged**
